In [2]:
import torch

x = torch.tensor([1, 2, 3])
print(x.max())

y = torch.tensor(
    [
        [1, 2, 3],
        [3, 2, 3],
    ]
)
print(y.max())
print(y.max(dim=0))
print(y.max(dim=1))

tensor(3)
tensor(3)
torch.return_types.max(
values=tensor([3, 2, 3]),
indices=tensor([1, 0, 0]))
torch.return_types.max(
values=tensor([3, 3]),
indices=tensor([2, 0]))


In [13]:
x = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ],
    ],
    dtype=torch.long,
)
x = x.float()
mean_result = x.mean()
print(mean_result)
mean_result = x.mean(dim=0)
print(mean_result)
mean_result = x.mean(dim=1)
print(mean_result)
mean_result = x.mean(dim=2)
print(mean_result)

tensor(6.5000)
tensor([[4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 2.5000,  3.5000,  4.5000],
        [ 8.5000,  9.5000, 10.5000]])
tensor([[ 2.,  5.],
        [ 8., 11.]])
