https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked


In [18]:
import torch

model = torch.hub.load(
    repo_or_dir="huggingface/pytorch-transformers",
    model="model",
    pretrained_model_name_or_path="distilbert-base-uncased",
)
model.config.pad_token_id

Using cache found in /Users/obov/.cache/torch/hub/huggingface_pytorch-transformers_main


0

In [25]:
input_ids = torch.tensor([[7592, 2057, 2097, 2393, 9611, 2115], [7592, 0, 0, 0, 0, 0]])
output1 = model(input_ids)
print(output1)

BaseModelOutput(last_hidden_state=tensor([[[ 0.3001,  0.5055, -0.1318,  ..., -0.4879, -0.8452,  0.2140],
         [ 0.2331,  0.3491, -0.1390,  ..., -0.3960, -0.2859,  0.0252],
         [ 0.2291,  0.0253, -0.0221,  ..., -0.2910, -0.0595, -0.0702],
         [-0.1747,  0.4513,  0.1002,  ..., -0.3464, -0.2671,  0.1382],
         [-0.1835,  0.4183,  0.2852,  ..., -0.1415, -0.1960,  0.3141],
         [-0.2379,  0.3317,  0.3834,  ...,  0.0327, -0.0470,  0.3877]],

        [[ 0.2520, -0.3201,  0.3655,  ..., -0.2526,  0.3130, -0.2502],
         [ 0.3022, -0.2151,  0.3503,  ..., -0.1660,  0.3403, -0.3780],
         [ 0.3166, -0.2242,  0.3420,  ..., -0.1793,  0.3316, -0.3833],
         [ 0.3270, -0.2421,  0.3442,  ..., -0.1860,  0.3369, -0.3898],
         [ 0.3335, -0.2635,  0.3544,  ..., -0.1930,  0.3576, -0.4066],
         [ 0.3360, -0.2824,  0.3636,  ..., -0.2015,  0.3685, -0.4142]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)


In [23]:
input_ids = torch.tensor([[7592]])
output2 = model(input_ids)
print(output2.last_hidden_state)

tensor([[[ 2.3278e-01,  4.7688e-01, -2.1987e-01,  3.7865e-01, -3.0753e-01,
          -2.9591e-01,  1.9465e-01,  7.3193e-01, -2.5531e-01,  2.1768e-01,
           6.8451e-02, -1.7196e-01, -2.4590e-01,  3.7573e-01, -6.7702e-01,
           8.5401e-01, -7.2232e-01,  4.8827e-01, -4.0099e-01,  1.7213e-01,
           2.6249e-01,  4.3922e-03,  1.3611e-01,  1.1130e-01, -5.9091e-02,
          -2.6408e-01, -1.8209e-01,  3.6750e-01, -2.2028e-01, -1.1873e-01,
          -4.0116e-01, -3.7263e-01,  4.7349e-01,  2.7298e-01, -3.5276e-01,
          -5.6177e-01,  9.4463e-01, -1.3907e-01, -4.9106e-01, -4.4841e-01,
          -4.1542e-01,  6.9512e-03,  2.1390e-01,  6.7661e-01,  6.4741e-01,
          -3.7991e-01,  5.3262e-01,  5.3981e-01,  5.1602e-01,  5.0126e-01,
          -2.4012e-01,  2.8672e-01,  2.8646e-01,  1.3572e-01,  3.4157e-01,
           6.0013e-01, -7.1519e-02, -9.8793e-01, -6.5276e-02,  9.3458e-03,
          -5.6433e-03,  1.2218e-01, -1.5343e-01, -4.3119e-01,  1.6644e-01,
           7.7296e-02, -5

In [28]:
input_ids = torch.tensor([[7592, 2057, 2097, 2393, 9611, 2115], [7592, 0, 0, 0, 0, 0]])
attention_mask = torch.tensor([[1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0]])
output3 = model(input_ids, attention_mask=attention_mask)
print(output3.last_hidden_state)
print(output3.last_hidden_state[:, 0])
print(output3.last_hidden_state[:, 0][..., 0])

tensor([[[ 0.3001,  0.5055, -0.1318,  ..., -0.4879, -0.8452,  0.2140],
         [ 0.2331,  0.3491, -0.1390,  ..., -0.3960, -0.2859,  0.0252],
         [ 0.2291,  0.0253, -0.0221,  ..., -0.2910, -0.0595, -0.0702],
         [-0.1747,  0.4513,  0.1002,  ..., -0.3464, -0.2671,  0.1382],
         [-0.1835,  0.4183,  0.2852,  ..., -0.1415, -0.1960,  0.3141],
         [-0.2379,  0.3317,  0.3834,  ...,  0.0327, -0.0470,  0.3877]],

        [[ 0.2328,  0.4769, -0.2199,  ..., -0.0581, -0.7123,  0.1947],
         [ 0.3244,  0.4633, -0.2135,  ..., -0.0797, -0.7053,  0.1202],
         [ 0.3040,  0.4531, -0.2033,  ..., -0.0923, -0.7214,  0.1124],
         [ 0.3103,  0.4410, -0.2037,  ..., -0.0985, -0.7337,  0.1153],
         [ 0.3089,  0.4411, -0.1998,  ..., -0.0983, -0.7324,  0.1153],
         [ 0.3091,  0.4351, -0.1958,  ..., -0.1012, -0.7316,  0.1165]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[ 0.3001,  0.5055, -0.1318,  ..., -0.4879, -0.8452,  0.2140],
        [ 0.2328,  0.4769, -0.2